apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: my-ec2
  namespace: my-crossplane
spec:
  forProvider:
    region: us-east-1
    imageId: ami-0dc2d3e4c0f9ebd18
    securityGroupRefs:
      - name: my-ec2-sg
    subnetIdRef:
      name: my-vpc-subnet1
  providerConfigRef:
    name: default
