apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-vpc-subnet1
  namespace: my-crossplane
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: my-vpc
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default
